# Generated by Django 3.1.7 on 2021-04-08 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bibm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Year_1',
            new_name='bibm_Year_1',
        ),
        migrations.RenameModel(
            old_name='Year_2',
            new_name='bibm_Year_2',
        ),
        migrations.RenameModel(
            old_name='Year_4',
            new_name='bibm_Year_3',
        ),
        migrations.RenameModel(
            old_name='Year_3',
            new_name='bibm_Year_4',
        ),
    ]
