# Generated by Django 3.1.7 on 2021-05-08 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bibm', '0002_auto_20210408_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibm_year_1',
            options={'verbose_name': 'bibm_Year_1', 'verbose_name_plural': 'bibm_Year_1'},
        ),
        migrations.AlterModelOptions(
            name='bibm_year_2',
            options={'verbose_name': 'bibm_Year_1', 'verbose_name_plural': 'bibm_Year_1'},
        ),
        migrations.AlterModelOptions(
            name='bibm_year_3',
            options={'verbose_name': 'bibm_Year_1', 'verbose_name_plural': 'bibm_Year_1'},
        ),
        migrations.AlterModelOptions(
            name='bibm_year_4',
            options={'verbose_name': 'bibm_Year_1', 'verbose_name_plural': 'bibm_Year_1'},
        ),
    ]
