# Generated by Django 3.1.7 on 2021-05-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, upload_to='galleries')),
            ],
            options={
                'verbose_name': 'campus',
                'verbose_name_plural': 'campus',
            },
        ),
        migrations.CreateModel(
            name='summer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, upload_to='galleries')),
            ],
            options={
                'verbose_name': 'summer',
                'verbose_name_plural': 'summer',
            },
        ),
        migrations.CreateModel(
            name='tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, upload_to='galleries')),
            ],
            options={
                'verbose_name': 'tour',
                'verbose_name_plural': 'tour',
            },
        ),
    ]
