# Generated by Django 3.1.7 on 2021-04-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bit', '0002_auto_20210405_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_year_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=150)),
                ('course_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course_year_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=150)),
                ('course_name', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Course',
            new_name='Course_year_1',
        ),
    ]
