# Generated by Django 3.1.7 on 2021-04-07 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bit', '0003_auto_20210406_1149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course_year_1',
            new_name='Year_1',
        ),
        migrations.RenameModel(
            old_name='Course_year_3',
            new_name='Year_2',
        ),
        migrations.RenameModel(
            old_name='Course_year_2',
            new_name='Year_3',
        ),
    ]
