# Generated by Django 3.1.7 on 2021-04-08 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bit', '0004_auto_20210407_2344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Year_1',
            new_name='bit_Year_1',
        ),
        migrations.RenameModel(
            old_name='Year_2',
            new_name='bit_Year_2',
        ),
        migrations.RenameModel(
            old_name='Year_3',
            new_name='bit_Year_3',
        ),
    ]
