# Generated by Django 3.1.7 on 2021-05-08 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bit', '0005_auto_20210408_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bit_year_1',
            options={'verbose_name': 'bit_Year_1', 'verbose_name_plural': 'bit_Year_1'},
        ),
        migrations.AlterModelOptions(
            name='bit_year_2',
            options={'verbose_name': 'bit_Year_2', 'verbose_name_plural': 'bit_Year_2'},
        ),
        migrations.AlterModelOptions(
            name='bit_year_3',
            options={'verbose_name': 'bit_Year_3', 'verbose_name_plural': 'bit_Year_3'},
        ),
    ]
